forms/urls.py
from django.urls import path, include
from .views import forms, savename, readmatkul

app_name = "forms"

urlpatterns = [
    path('', forms, name='forms'),
    path('savename', savename, name='savename'),
    path('readmatkul', readmatkul, name='readmatkul')
]

kegiatan/urls.py
from django.urls import path, include
from .views import kegiatan, formKgt, formPst, delete

app_name = "kegiatan"

urlpatterns = [
    path('', kegiatan, name='kegiatan'),
    path('buatkgt/', formKgt, name='formKgt'),
    path('buatpst/<int:id_kegiatan>', formPst, name='formPst'),
    path('hapus/<int:id_kegiatan>/', delete, name='delete'),
]

old/urls.py
from django.urls import path, include
from .views import page

app_name = "old"

urlpatterns = [
    path('', page, name='page'),
]

ppw/urls.py
from django.urls import path, include
from .views import index, education, theman, specialties, experiences, contacts

urlpatterns = [
    path('', index, name='index'),
    path('theman.html/', theman, name='theman'),
    path('education.html/', education, name='education'),
    path('experiences.html/', experiences, name='experiences'),
    path('specialties.html/', specialties, name='specialties'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw.urls')),
    path('old/', include(('old.urls', 'old'), namespace='old')),
    path('forms/', include(('forms.urls', 'forms'), namespace='forms')),
    path('kegiatan/', include(('kegiatan.urls', 'kegiatan'), namespace='kegiatan')),
    path('story7/', include(('story7.urls', 'story7'), namespace='story7')),
    path('searching/', include(('searching.urls', 'searching'), namespace='searching')),
    path('regis/', include(('regis.urls', 'regis'), namespace='regis')),
]

ppw/models.py
from django.db import models

# Create your models here.

ppw/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')
def education(request):
    return render(request, 'education.html')
def theman(request):
    return render(request, 'theman.html')
def specialties(request):
    return render(request, 'specialties.html')
def experiences(request):
    return render(request, 'experiences.html')
def contacts(request):
    return render(request, 'contacts.html')

ppw/templates/base.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position:static">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'theman' %}">Biography</a>
        <a class="nav-item nav-link" href="{% url 'education' %}">Education</a>
        <a class="nav-item nav-link" href="{% url 'experiences' %}">Experiences</a>
        <a class="nav-item nav-link" href="{% url 'specialties' %}">Specialties</a>
        <a class="nav-item nav-link" href="{% url 'forms:forms' %}">Forms</a>
      </div>
    </div>
  </nav>

ppw/templates/education.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/minime.jpg' %}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Yellowtail&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>His Educational Background</title>
</head>
<body>
    <div class="parent">
        {% include "base.html" %}
        <img class="image1 img-fluid" style="width:500px;" src="{% static 'images/fullbook.png' %}">
    </div>
    <div id="side">
        <h1 id="title">His Educational Background</h1>
        <p>&nbsp;</p>
        <img style="width:90%; padding-left: 40px;" src="{% static 'images/branch-min.png' %}" alt="IfItDoesntMatchAnyMedia">
    </div>
</body>
</html>

ppw/templates/experiences.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/minime.jpg' %}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Yellowtail&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>His Experiences</title>
</head>
<body>
    <div class="parent">
        {% include "base.html" %}
        <img class="image1 img-fluid" style="width:500px;" src="{% static 'images/fullmap.png' %}">
    </div>
    <div id="side2">
        <h1 id="title">His Experiences</h1>
        <p>&nbsp;</p>
            <div class="row">
            <div class="column">
                <h2 style="font-weight: 1000;">Media Komunikasi</h2>
                <h3 style="font-weight: 300;">Head of Extracuriccular</h3>
            </div>
            <div class="column" style="margin-top:25px">
                <h3>2017 - 2018</h3>
            </div>
        </div>
        <p>&nbsp;</p>
        <div class="row">
            <div class="column">
                <h2 style="font-weight: 1000;">Rohani Islam</h2>
                <h3 style="font-weight: 300;">Member</h3>
            </div>
            <div class="column" style="margin-top:25px">
                <h3>2016 - 2018</h3>
            </div>
        </div>
        <p>&nbsp;</p>
        <div class="row">
            <div class="column">
                <h2 style="font-weight: 1000;">AIESEC in Universitas Indonesia</h2>
                <h3 style="font-weight: 300;"> Team Member of<BR>Product Marketing oGX</h3>
            </div>
            <div class="column" style="margin-top:25px">
                <P>&nbsp;</P>
                <h3>2019 - Now</h3>
            </div>
        </div>
        <p>&nbsp;</p>
        <div class="row">
            <div class="column">
                <h2 style="font-weight: 1000;">DPM Fasilkom UI</h2>
                <h3 style="font-weight: 300;">Member</h3>
            </div>
            <div class="column" style="margin-top:25px">
                <h3>2019 - Now</h3>
            </div>
        </div>
    </div>
</body>
</html>

ppw/templates/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" initial-scale=1.0, maximum-scale=1.0, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/minime.jpg' %}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Yellowtail&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Fauzan's Biography</title>
</head>
<body>
    <h1 id="intro">A Biography<br>of That One Guy</h1>
    <p>&nbsp;</p>
    <h2>Hello Everyone! This is Fauzan's Biography</h2>
    <p>&nbsp;</p>
    <p id=title>In this website, you will see most of my information, whether it's my identification, educational history, or my personal contact information.</p>
    <p>&nbsp;</p>
    <div style="display:block;" class="hover08">
        <a href="./theman.html">
        <figure><img src="{% static 'images/myface.png' %}" alt="My Face" class="left img-fluid"></figure>
        </a>
        <h1 id="theman">The Man<br>Himself</h1>
    </div>
    <p>&nbsp;</p>
    <div style="display:block;" class="hover08">
        <a href="./specialties.html">
        <figure><img src="{% static 'images/specialties.png' %}" alt="Some Laptop" class="right img-fluid"></figure>
        </a>
        <h1 id="text-left">His<br>Specialties</h1>
    </div>
    <p>&nbsp;</p>
    <div style="display:block;" class="hover08">
        <a href="./education.html">
        <figure><img src="{% static 'images/education.png' %}" alt="Some Books" class="left img-fluid"></figure>
        </a>
        <h1 id="education">His<br>Educational<br>Background</h1>
    </div>
    <p>&nbsp;</p>
    <div style="display:block;" class="hover08">
        <a href="./experiences.html">
        <figure><img src="{% static 'images/experience.png' %}" alt="A Map" class="right img-fluid"></figure>
        </a>
        <h1 id="text-left">His<br>Experiences</h1>
    </div>
    <p>&nbsp;</p>
    <div style="display:block;" class="hover08">
        <a href="{% url 'forms:forms' %}">
        <figure><img src="{% static 'images/forms.png' %}" alt="Form" class="left img-fluid"></figure>
        </a>
        <h1 id="education">A Form<br>Filled with<br>Stuff</h1>
    </div>
    <p>&nbsp;</p>
    <div style="background-color: #fbe2e5; padding-top: 50px; padding-bottom: 50px;">
        <h2 id="footer">Like what you see?<br>Consider contact this guy at</h2>
        <div class="baris" style="width:30%; margin-left: auto; margin-right: auto;">
            <div class="kolom">
                <a href="https://www.instagram.com/muhrizfau/">
                    <img src="{% static 'images/instagram.png' %}" alt="Instagram" style="width:100%;">
                </a>
            </div>
            <div class="kolom">
                <a href="https://twitter.com/muhrizfau">
                    <img src="{% static 'images/twitter.png' %}" alt="Twitter" style="width:100%;">
                </a>
            </div>
            <div class="kolom">
                <a href="https://gitlab.com/rfauzan46">
                    <img src="{% static 'images/gitlab.png' %}" alt="Gitlab" style="width:100%;">
                </a>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <a class="btn btn-dark" href="{% url 'old:page' %}" role="button">Click here to see the old version</a>
        </div>
        <p>&nbsp;</p>
        <div class="d-flex justify-content-center">
            <a class="btn btn-outline-dark" href="{% url 'kegiatan:kegiatan' %}" role="button">Click here to see activity function (Story6)</a>
        </div>
    </div>
</body>
</html>

ppw/templates/specialties.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/minime.jpg' %}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Yellowtail&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>His Specialties</title>
</head>
<body>
    <div class="parent">
        {% include "base.html" %}
        <img class="image1 img-fluid"  id src="{% static 'images/fulllaptop.png' %}">
    </div>
    <div id="side">
        <h1 id="title">His<br>Specialties</h1>
        <p>&nbsp;</p>
        <h2 style="font-weight: 1000;" id="title">HARD SKILLS</h2>
        <p>&nbsp;</p>
        <div class="row">
            <div class="column">
                <h2>Graphic Design</h2>
                <p id="content">Graphic Design is My Passion, so they say. But it’s true.
                He’s been learning the basics of design since He was in Middle School, 
                also with that He has gone to several graphic design competitions such as poster and others.</p>
            </div>
            <div class="column">
                <h2>Basic Programming</h2>
                <p id="content">Based on a year of experience in Computer Science, Python has been his favorite language to learn, and also the one he understands the most.
                He has built several projects with Python that you can see on his Gitlab.</p>
            </div>
        </div>
        <p>&nbsp;</p>
        <div class="row">
            <div class="column">
                <h2>Web Design</h2>
                <p id="content">He spents most of his time learning the fundamentals of web design, understanding people’s needs in a program, and how they interact with it. 
                He has 1+ years of experience in HTML and CSS Web Programming.</p>
            </div>
            <div class="column">
                <h2>Video Editing</h2>
                <p id="content">Aside from graphic design, He also happens to have certain experience with video editing. 
                He has more then 5 years of experience in Vegas Pro. Also, he was once the school’s social media  content manager.</p>
            </div>
        </div>
        <p>&nbsp;</p>
        <h2 style="font-weight: 1000;" id="title">SOFT SKILLS</h2>
        <p>&nbsp;</p>
        <div class="row">
            <div class="column">
                <h2>Team Player</h2>
                <p id="content">He always has been a team player. He always make sure his teammates finshes their jobs if he already finishes his. 
                Also, he easy to chat with, so don’t be afraid with awkwardness.</p>
            </div>
            <div class="column">
                <h2>Public Speaking</h2>
                <p id="content">He has a podcast called <a href="https://open.spotify.com/show/7aWU7wClxYH33ZWnoSGI1I">Awakward Podcast</a> that he created from 2018. 
                With that, he has an ability to speak fluently as a speaker, and enough confidence to convice people to hear his words.</p>
            </div>
        </div>
    </div>
</body>
</html>

ppw/templates/theman.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="../static/images/minime.png" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Yellowtail&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/home/style.css">
    <title>The Man Himself</title>
</head>
<body>
    <div class="parent">
        {% include "base.html" %}
        <img class="image1 img-fluid" style="width:500px;" src="../static/images/fullface.png">
    </div>
    <div id="side">
        <h1 id="title">The Man<br>Himself</h1>
        <p>&nbsp;</p>
        <p id="desc">Muhammad Rizki Fauzan is fine young gentleman who was born on July 27, 2001 in Jakarta. 
        Throughout his life, he always has a spark of interest in computing, whether it's about electrical stuff, or coding itself. 
        Ever since he understands what requirements are needed to learn computing, he learns a lot of math. 
        His interest of math and computing was continued to the point he got accepted to Computer Science Undergraduate Program in Universitas Indonesia in 2019. 
        Currently, he's learning web development, and this is one of his projects.
        </p>
        <p>&nbsp;</p>
        <ul>
            <li>Name: Muhammad Rizki Fauzan</li>
            <li>NPM: 1906400375</li>
            <li>Occupation: Student of Computer Science in Universitas Indonesia (2019)</li>
            <li>Hobbies: Watching YouTube Videos, Podcasting, Design</li>
        </ul>
    </div>
    
</body>
</html>