forms/urls.py
from django.urls import path, include
from .views import forms, savename, readmatkul

app_name = "forms"

urlpatterns = [
    path('', forms, name='forms'),
    path('savename', savename, name='savename'),
    path('readmatkul', readmatkul, name='readmatkul')
]

old/urls.py
from django.urls import path, include
from .views import page

app_name = "old"

urlpatterns = [
    path('', page, name='page'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw.urls')),
    path('old/', include(('old.urls', 'old'), namespace='old')),
    path('forms/', include(('forms.urls', 'forms'), namespace='forms')),
    path('kegiatan/', include(('kegiatan.urls', 'kegiatan'), namespace='kegiatan')),
    path('story7/', include(('story7.urls', 'story7'), namespace='story7')),
    path('searching/', include(('searching.urls', 'searching'), namespace='searching')),
    path('regis/', include(('regis.urls', 'regis'), namespace='regis')),
]

forms/models.py
from django.db import models

SMT_CHOICES = [
    ('Gasal (2019/2020)', 'Gasal (2019/2020)'),
    ('Genap (2019/2020)', 'Genap (2019/2020)'),
    ('Gasal (2020/2021)', 'Gasal (2020/2021)'),
    ('Genap (2020/2021', 'Genap (2020/2021)'),
]

class Matkul(models.Model):
    name = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.PositiveSmallIntegerField()
    desc = models.TextField(max_length=200)
    smt = models.CharField(max_length=17, choices=SMT_CHOICES)
    ruang = models.PositiveSmallIntegerField()

forms/admin.py
from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Matkul)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/forms.py
from django import forms
from .models import Matkul

SMT_CHOICES = [
    ('Gasal (2019/2020)', 'Gasal (2019/2020)'),
    ('Genap (2019/2020)', 'Genap (2019/2020)'),
    ('Gasal (2020/2021)', 'Gasal (2020/2021)'),
    ('Genap (2020/2021', 'Genap (2020/2021)'),
]

class Input_Form(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['name', 'dosen', 'sks', 'desc', 'smt', 'ruang']

    error_messages = {
        'required' : 'Tolong diisi'
    }

    name_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Nama Mata Kuliah'
    }

    dosen_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Nama Dosen'
    }

    sks_attrs = {
        'type':'number',
        'class':"form-control",
        'placeholder':'Jumlah SKS'
    }

    desc_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Deskripsi Mata Kuliah'
    }

    smt_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Semester'
    }

    ruang_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Ruang Belajar'
    }

    name = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    dosen = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=dosen_attrs))
    sks = forms.IntegerField(label='', required=True, widget=forms.TextInput(attrs=sks_attrs))
    desc = forms.CharField(label='', required=True, max_length=200, widget=forms.Textarea(attrs=desc_attrs))
    smt = forms.CharField(label='', required=True, max_length=17, widget=forms.Select(choices=SMT_CHOICES))
    ruang = forms.IntegerField(label='', required=True, widget=forms.TextInput(attrs=ruang_attrs))

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import Matkul
# Create your views here.


def forms(request):
    response = {'input_form': Input_Form}
    return render(request,'forms.html', response)

def savename(request):
    form = Input_Form(request.GET or None)
    if (form.is_valid and request.method == 'GET'):
        form.save()
        return HttpResponseRedirect('./readmatkul')
    else:
        return HttpResponseRedirect('/')

def readmatkul(request):
    matkuls = Matkul.objects.all()
    response = {'matkuls' : matkuls}
    html = 'forms.html'
    return render(request, html, response)

forms/templates/base.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position:static">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'theman' %}">Biography</a>
        <a class="nav-item nav-link" href="{% url 'education' %}">Education</a>
        <a class="nav-item nav-link" href="{% url 'experiences' %}">Experiences</a>
        <a class="nav-item nav-link" href="{% url 'specialties' %}">Specialties</a>
        <a class="nav-item nav-link" href="{% url 'forms:forms' %}">Forms</a>
      </div>
    </div>
  </nav>

forms/templates/forms.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href=".{% static 'images/minime.jpg' %}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Yellowtail&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>A Form Filled With Stuff</title>
</head>
<body>
    <div class="parent">
        {% include "base.html" %}
        <img class="image1 img-fluid" style="width:500px;" src="{% static 'images/fullform.png' %}">
    </div>
    <div id="side">
        <h1 id="title">A Form<br>Filled with Stuff</h1>
        <p>&nbsp;</p>
        <form action="savename" method="GET">
            <div class="form-group">
                {% csrf_token %}
                {{ input_form.as_p }}
            <button type="submit" class="btn btn-dark" style="margin-left:50px">Submit</button>
            </div>
        </form>
        <p>&nbsp;</p>
        {% if matkuls %}
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Nomor</th>
                <th scope="col">Mata Kuliah</th>
                <th scope="col">Nama Dosen</th>
                <th scope="col">Jumlah SKS</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Semester Tahun</th>
                <th scope="col">Ruang Kelas</th>
              </tr>
            </thead>
            {% for matkul in matkuls %}
            <tbody>
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ matkul.name }}</td>
                <td>{{ matkul.dosen }}</td>
                <td>{{ matkul.sks }}</td>
                <td>{{ matkul.desc }}</td>
                <td>{{ matkul.smt }}</td>
                <td>{{ matkul.ruang }}</td>
              </tr>
            </tbody>
                {% endfor %}
            {% endif %}
        </table>
        <div class="d-flex justify-content-center">
          <a class="btn btn-light" href="{% url 'forms:readmatkul' %}" role="button">Click here to see the results</a>
      </div>
    </div>
    
</body>
</html>